### ISSUE TITLE
Bug: Can only run 1 docsify at a time

### ISSUE THREAD

**Issue by jgraup** [QingWei-Li/docsify-cli#15]
First of all, docsify is awesome and so is this cli. My only problem is that I want to run multiple generated docs on various ports. When I specify a port other than the last `docsify serve` I am presented with an exception. This happens locally and on my remote server where I want many documents to co-exist. Locally I just want to be able to edit 1-2. Remotely I am pushing more.

Is there something I am missing to allow this to happen, or is this something that needs to be fixed. 

The current work-around in my setup is to run a basic static nodejs server with [`forever`](https://github.com/foreverjs/forever).

Here is the error I am seeing after running `docsify serve . --port 3000` then `docsify serve . --port 4000`:
```
Listening at http://localhost:4000

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::35729
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at Server.listen (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:66:28)

    at Object.exports.createServer (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:224:14)
    at Object.module.exports [as serve] (/usr/local/lib/node_modules/docsify-cli/lib/commands/serve.js:29:12)
    at Object.handler (/usr/local/lib/node_modules/docsify-cli/bin/docsify:69:28)
    at Object.self.runCommand (/usr/local/lib/node_modules/docsify-cli/node_modules/yargs/lib/command.js:231:22)
```

Thanks in advance!

**Comment by jgraup** [comment]
It looks like this issue is common: [A](https://github.com/ionic-team/ionic-cli/issues/1678#issuecomment-261683261), [B](https://github.com/ionic-team/ionic-app-scripts/issues/421), [C](https://github.com/ionic-team/ionic-app-scripts/issues/383). 

Is it possible to support passing [port](https://github.com/napcs/node-livereload#api-options) info to [`livereload()`](https://github.com/QingWei-Li/docsify-cli/blob/3f488d0d4731ddc77210e2a1f4bdcb41687e43e3/lib/commands/serve.js#L26) as an extra argument?
```
--livereload-port 35730
```
