### ISSUE TITLE
Error occurs when docsify serve two folder at same time

### ISSUE THREAD

**Issue by mixj93** [QingWei-Li/docsify-cli#25]
I have two docsify docs in two folder. When I serve one docs, everything seems fine, but when I start serving the second one, error occurs:
```
▶ docsify serve . -p 2334
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***

Serving /Users/lixueli/work/qbox/hub-docs now.
Listening at http://localhost:2334

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::35729
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Server.listen (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:69:28)
    at Object.exports.createServer (/usr/local/lib/node_modules/docsify-cli/node_modules/livereload/lib/livereload.js:229:14)
    at Object.module.exports [as serve] (/usr/local/lib/node_modules/docsify-cli/lib/commands/serve.js:29:12)
    at Object.handler (/usr/local/lib/node_modules/docsify-cli/bin/docsify:77:28)
    at Object.self.runCommand (/usr/local/lib/node_modules/docsify-cli/node_modules/yargs/lib/command.js:231:22)
```

Thanks for any help.

**Comment by mixj93** [comment]
docsify version:
```
▶ docsify -v

docsify-cli version:
  4.1.11
```

**Comment by QingWei-Li** [comment]
Because this `livereload port` is used.

You can do this

```sh
docsify  serve . -p 2334 -P 35730
```

**Comment by mixj93** [comment]
thx a lot, problem solved.

**Comment by mixj93** [comment]
it seems only -P 35729 will reload page automatically, other port not auto reload.

**Comment by mixj93** [comment]
create a new issue: https://github.com/QingWei-Li/docsify-cli/issues/26

**Comment by Brannua** [comment]
> Because this `livereload port` is used.
> 
> You can do this
> 
> ```shell
> docsify  serve . -p 2334 -P 35730
> ```

Excuse me, 

I only serve just one document using docsify listening on port 3000 currently

but the live-reload is not available unless i change the port, such as execute `docsify serve . -p 1234`

Why I can not use the defalut port 3000 ?

And how can I detect live-reload port is being used ?

Thanks~
